### ISSUE TITLE
Mistakes

### ISSUE THREAD

**Issue by chenat9** [Range0122/range0122.github.io#2]
I hava found a mistake from your note
_Shard Locks_ and _Exclusive Locks_ are two concepts in  Database,(for example mysql / rocksdb) so they should not be included in OS subject.
Also，_Table-Level Locks_ and _Row-Level Locks_ are same as above.

**Comment by Range0122** [comment]
Thanks, I'll fix it later.

**Comment by Range0122** [comment]
Structure of directory has been fixed: a new directory Database is created.
